name: Windows Build

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  windows:
    name: "Build Windows x64"
    runs-on: windows-2022
    steps:
      - name: Get AV
        uses: actions/checkout@v3
        with:
          path: main
      - name: Get MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build AV
        run: msbuild build\VisualStudio\ArrowVortex.vcxproj /p:Configuration=Release /p:Platform=x64
      - name: Obtain oggenc2.exe
        run: >
          curl https://www.rarewares.org/files/ogg/oggenc2.88-1.3.7-x64.zip --output oggenc.zip &&
          unzip oggenc.zip -d .
      - name: Collect into a zip
        run: >
          mkdir AV &&
          cd AV &&
          cp ../bin/assets . &&
          cp ../bin/noteskins . &&
          cp ../bin/settings . &&
          cp ../bin/ArrowVortex.exe .
          cp ../oggenc2.exe . &&
          cd .. &&
          zip -r ArrowVortex-`date +%Y-%m-%d`.zip AV      
